Add polaroid camera
CodenameAlphamale/FaultWithCuriosity pull request #46
Opened 2023-04-26 14:15 UTC by kenandizdarevic

Polaroid camera has been added.

Take picture with mouseleft and a polaroid will drop. Player can interact with the polaroid by pressing interaction key.

2023-04-26 14:26 UTC, Cactooz requested changes
- [x] You have unlimited camera charges.
- [x] The polaroids have purple image on the item.
- [x] "Press E to view" shows up on the images.
- [x] The camera takes an image if you left click even in the inventory.

2023-04-26 14:27 UTC, kenandizdarevic commented
- No
- No
- No
- No
@Cactooz

2023-04-26 14:30 UTC, Cactooz commented
If you take up the original image in the testing scene, then you can't take any more images at all. Throwing an error that the object is missing. Spawn a prefab instead.

2023-04-26 14:43 UTC, Cactooz requested changes
More code requests. Please see the points above with Unity 3D/testing errors.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/CameraMovement.cs
> +    [SerializeField] public Transform person;
Huh? Why is it public?

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/Item Scripts/PolaroidItem.cs
> +	public void OnInteract() {
Remove this if its unused.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/ItemCamera.cs
> +	[SerializeField] private KeyCode rechargeCameraButton = KeyCode.Mouse2;
Remove the rechargeCameraButton, it should be made through the inventory now.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/ItemCamera.cs
> +		UseCamera();
Have an if-statement with the canUsseCamera here instead of in the UseCamera method.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/ItemCamera.cs
> +				// amount of recharges
Github Copilot? Stupid comment...

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/PlayerActions.cs
> +			//uiText.text = "Press " + actionButton + " to use";
Remove code comments.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/PlayerActions.cs
> +			//uiText.text = "";
Remove whole else statement with the comment.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/PlayerActions.cs
> +			if(Input.GetKeyDown(actionButton))
Put this if statement in the parent statement instead of having nested ones.

2023-04-26 14:43 UTC, Cactooz commented on Assets/Scripts/PlayerActions.cs
Remove this whole script, it should probably not be used anymore. Though make sure to test after you have removed this script.

2023-04-27 06:46 UTC, kenandizdarevic commented on Assets/Scripts/Item Scripts/PolaroidItem.cs
> +	public void OnInteract() {
Needs to be in the code, the interface **IIterable** will not work if it is removed.

2023-04-27 07:15 UTC, Cactooz commented on Assets/Scripts/Item Scripts/PolaroidItem.cs
> +	public void OnInteract() {
Ah ok makes sense!

2023-04-27 07:22 UTC, Cactooz requested changes
Everything works but update the Player Aaron prefab with the new changes!

2023-04-27 07:27 UTC, Cactooz approved these changes
Works now!

2023-04-27 07:28 UTC, merged